### ISSUE TITLE
Stacktrace lost?

### ISSUE THREAD

**Issue by danigb** [dy/tst#1]
Hi,

Thanks for this library. I like the simplicity and size. However, I don't know why, stack traces are lost. The test is sync and very simple:

```js
test('generate', function() {
  const array = myLibrary.generateArray();
  assert.deepEqual(array, [0, 1, 2, 3, 4]);
});
```

And the result is:

```
 × generate
AssertionError:
deepEqual
0,1,2,3,4,5,6,7,8,9
```

Thats all.

Any idea of why this is happening? Thanks in advance.

**Comment by dy** [comment]
Resolved in 3.0.0.

In some reason, displaying correct stack trace with sourcemaps included in browsers is tricky part.
Turns out only `console.error(error.stack)` (not `console.error(error)` nor `console.error(smth, error.stack)`) and `console.assert(false, msg, error)` work.
